# Generated by Django 5.1.1 on 2024-09-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Title')),
                ('tag', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tag')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='image/')),
                ('user_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Username')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
    ]
