# Generated by Django 5.1.1 on 2024-09-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog_model_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_model',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
